title: prueba
description: prueba just the docs
theme: just-the-docs

url: https://HuberGiron.github.io/just

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/HuberGiron/prueba_just/
  
