title: "prueba"
description: "prueba just the docs"
theme: just-the-docs

url: "https://HuberGiron.github.io"
baseurl: "/just"

aux_links:
  Template Repository: "https://github.com/HuberGiron/prueba_just/"
  
permalink: pretty
search_enabled: true

# (Opcional) Mermaid para diagramas
# plugins:
#   - jekyll-mermaid

nav_external_links:
  - title: "Volver al sitio principal"
    url: "/"
