title: "prueba"
description: "prueba just the docs"
theme: just-the-docs

url: "https://hubergiron.github.io"
baseurl: "/prueba_just"

permalink: pretty
search_enabled: true

aux_links:
  Template Repository: "https://github.com/HuberGiron/prueba_just/"

nav_external_links:
  - title: "Volver al sitio principal"
    url: "/"
